M48
; DRILL file {KiCad (5.99.0-10483-ga6ad7a4a70)} date Sun May 23 17:26:48 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-05-23T17:26:48+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10483-ga6ad7a4a70)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.4549Y-4.0407
X4.4549Y-4.2683
T0
M30
